### PR TITLE
Sso/story provider invalidate

### PR DESCRIPTION
**Pull request by joshualan**
Changes include:

* Added an error message
* Added invalidate() on the AuthenticationProvider
* Added a check in _getToken() to throw an error if token was invalidated
* Minor changes

### CODE REVIEW

**Comment by whenshaw** [comment]
1. jsdoMSG126 -- maybe better to just say "The AuthenticationProvider does not have a valid token."? (It's true that, given our current code, this message won't be used unless there had previously been a successful authentication, but I wonder if that will always be the case. )
2. Had some thoughts/questions on _getToken. Maybe it should it do just one thing -- return the value of the token, no matter what it is, even if it's null. Then we have another one ( _getValidToken?) that throws an error if there's no valid token. And I wonder whether we need the retrieveToken() function, or should just bite the bullet and define the _getToken method in the AuthenticationProvider's constructor.

**Comment by joshualan** [comment]
Edited the code to have the three things we wanted:

* Edited the error message
* Moved _getToken to progress.auth.js and to not throw errors and only return the values
* Added error checking in addTokenToRequest()

**Comment by whenshaw** [comment]
Looks good except I don't see the error message change. Is there a commit you still need to do for progress.js?

**Comment by whenshaw** [comment]
As I commented at GitHub, I didn’t see the error message change. I’m going to sit with Steve now for a few minutes, will check back in a bit.

**Comment by joshualan** [comment]
Edited the error message! Hopefully last commit, fingers crossed.

**Comment by whenshaw** [comment]
Everything looks good. Remember to set the version numbers of the individual files before checking them into ClearCase.

**Pull request merged**
